#!/bin/bash

# Will copy all the static files into the ./staticfiles folder
python ./manage.py collectstatic --settings botify_docs.settings.local

# run django medusa to generate the html files into the ./_site folder
python ./manage.py staticsitegen --settings botify_docs.settings.local
